# Slicing

In [2]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[1:5])

[20 30 40 50]


In [4]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[3:6])   # index always start with 0

[40 50 60]


# Not specify end value

In [5]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[2:])

[30 40 50 60 70 80]


# Not specify start value

In [6]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[ : 6])

[10 20 30 40 50 60]


# Negative slicing

In [8]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[-6 :-1])

[30 40 50 60 70]


In [9]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[-3 :-1])

[60 70]


In [10]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[2 :-3])

[30 40 50]


# Slicing with step values

In [12]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[0:6:2])

[10 30 50]


In [13]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[0:7:3])

[10 40 70]


# Print all elements

In [14]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[::])

[10 20 30 40 50 60 70 80]


In [15]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print(i[ : : 2 ])

[10 30 50 70]


# Slicing with 2-D Arrays

In [17]:
import numpy as np

i = np.array([
    [10, 20, 30, 40, 50],     # 0 - 0 1 2 3 4
    [60, 70, 80, 90, 100]     # 1 - 0 1 2 3 4
])

print(i[1, 0:3])

[60 70 80]


In [18]:
import numpy as np

i = np.array([
    [10, 20, 30, 40, 50],     # 0 - 0 1 2 3 4
    [60, 70, 80, 90, 100]     # 1 - 0 1 2 3 4
])

print(i[0, 1:4])

[20 30 40]


In [21]:
import numpy as np

i = np.array([
    [10, 20, 30, 40, 50],     # 0 - 0 1 2 3 4
    [60, 70, 80, 90, 100],    # 1 - 0 1 2 3 4
    [11, 22, 33, 44, 55]      # 2 - 0 1 2 3 4
])

print(i[2, 1:4])

[22 33 44]


In [22]:
import numpy as np

i = np.array([
    [10, 20, 30, 40, 50],    # 0 - 0 1 2 3 4
    [60, 70, 80, 90, 100],   # 1 - 0 1 2 3 4
    [11, 22, 33, 44, 55]     # 2 - 0 1 2 3 4
])

print(i[0:2, 1])

[20 70]


In [23]:
import numpy as np

i = np.array([
    [10, 20, 30, 40, 50],    # 0 - 0 1 2 3 4
    [60, 70, 80, 90, 100],   # 1 - 0 1 2 3 4
    [11, 22, 33, 44, 55]     # 2 - 0 1 2 3 4
])

print(i[0:2, 1])

[20 70]


In [26]:
import numpy as np

i = np.array([
    [10, 20, 30, 40, 50],    # 0 - 0 1 2 3 4
    [60, 70, 80, 90, 100],   # 1 - 0 1 2 3 4
    [11, 22, 33, 44, 55],    # 2 - 0 1 2 3 4
    [1, 2, 3, 4, 5]          # 3 - 0 1 2 3 4
])

print(i[0:4, 0:3])

[[10 20 30]
 [60 70 80]
 [11 22 33]
 [ 1  2  3]]


In [27]:
import numpy as np

i = np.array([
    [10, 20, 30, 40, 50],    # 0 - 0 1 2 3 4
    [60, 70, 80, 90, 100],   # 1 - 0 1 2 3 4
    [11, 22, 33, 44, 55],    # 2 - 0 1 2 3 4
    [1, 2, 3, 4, 5]          # 3 - 0 1 2 3 4
])

print(i[0:2, 2:4])

[[30 40]
 [80 90]]


In [28]:
import numpy as np

i = np.array([
    [10, 20, 30, 40, 50],    # 0 - 0 1 2 3 4
    [60, 70, 80, 90, 100],   # 1 - 0 1 2 3 4
    [11, 22, 33, 44, 55],    # 2 - 0 1 2 3 4
    [1, 2, 3, 4, 5]          # 3 - 0 1 2 3 4
])

print(i[0:3, -3:-1])

[[30 40]
 [80 90]
 [33 44]]


# Check Data type

In [29]:
import numpy as np

i = np.array([10, 20, 30, 40, 50])

print(i.dtype)

int32


In [30]:
import numpy as np

i = np.array([10.1, 20.1, 30.1, 40.1, 50.1])

print(i.dtype)

float64


In [32]:
import numpy as np

i = np.array([10.1, 20.1, 30.1, 40.1, 'Hello'])

print(i.dtype)

<U32


In [33]:
import numpy as np

i = np.array(['a','b','c'])

print(i.dtype)

<U1


# Convert data type values

In [36]:
import numpy as np

i = np.array([10.10, 20.20, 30.30])

i1 = i.astype('i')

print(i1.dtype)

print()

print(i1)


int32

[10 20 30]


In [38]:
import numpy as np

i = np.array([10, 20, 30])

i1 = i.astype('f')

print(i1)

print()

print(i1.dtype)

[10. 20. 30.]

float32


# Check Shape of Array

In [40]:
import numpy as np

i  = np.array([10,20,30])

print(i.shape)

print(i.dtype)

(3,)
int32


In [41]:
import numpy as np

i  = np.array([
    [10,20,30],
    [40,50,60]
])

print(i.shape)

print(i.dtype)

(2, 3)
int32


In [42]:
import numpy as np

i  = np.array([
    [[10,20,30], [1,2,3]],
    [[40,50,60], [4,5,6]]
])

print(i.shape)

print(i.dtype)

(2, 2, 3)
int32


# numpy.zeros() 

In [48]:
import numpy as np

i = np.zeros((2,2))

i

array([[0., 0.],
       [0., 0.]])

# numpy.ones() 

In [49]:
import numpy as np

i = np.ones((1,2,3))

i

array([[[1., 1., 1.],
        [1., 1., 1.]]])